package com.nylas.models

import com.squareup.moshi.Json

/**
 * Class representing a response to a message composition request.
 */
data class ComposeMessageResponse(
  /**
   * The message suggestion generated by smart compose.
   */
  @Json(name = "suggestion")
  val suggestion: String,
)
